### ISSUE TITLE
Run the model and make Documentation

### ISSUE THREAD

**Issue by shivamsouravjha** [shivamsouravjha/-PetFinder.my-Adoption-Prediction-#1]
be sure to be assigned before working

**Comment by abhinav-193** [comment]
I want to work on it. Can you please assign me?

**Comment by shivamsouravjha** [comment]
done @abhinav-193

**Comment by abhinav-193** [comment]
Thank you

**Comment by heythere12** [comment]
Would like to take over this issue! @shivamsouravjha

**Comment by shivamsouravjha** [comment]
@heythere12 the documentation part is already done, so either you can improve the accuracy score of the model or help enhance documentation of my other project [Sign-language-digit-dataset](https://github.com/shivamsouravjha/TFLite-creator-with-Kaggle-dataset-in-colab/issues)

**Comment by heythere12** [comment]
I'll enhance the accuracy score!

**Comment by shivamsouravjha** [comment]
@heythere12 GREAT assigned it to you.

**Comment by shivamsouravjha** [comment]
@heythere12 I've shifted my repo to a collab file. So to access data (csv files in my model ,use the  train,test and submission csv from [this link](https://www.kaggle.com/c/petfinder-adoption-prediction/data)  (download only 3 csv train,test,submission)
